# Generated by Django 3.0.7 on 2020-10-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitme', '0005_image_for_ml_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_for_ml',
            name='user',
        ),
    ]
